version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@@4.7

jobs:
  print_hello:
    docker:
      - image: cimg/node:16.10
    steps:
      - run:
          name: Run print_hello
          command: echo "hello"

  print_world:
    docker:
      - image: cimg/node:16.10
    steps:
      - run:
          name: Run print_world
          command: echo "world"


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello