version: 2.1
# Use a package of configuration called an orb.

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:16.10
    working_directory: /tmp
    steps:
      - run: mkdir -p workspace
      - run: echo "hello world" > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output

  print_hello_world:
    docker:
      - image: cimg/node:16.10
    working_directory: /tmp
    steps:
      - attach_workspace:
         at: /tmp/workspace

      - run: |
          if [[ 'cat /tmp/workspace/echo-output' == "hello world" ]]; then
            echo "hello world";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_hello_world:
          requires:
            - save_hello_world_output